---
# module: refstack_install/tasks/install
# description: Install our required packages for RefStack

- name: Install all required packages for RefStack
  apt:
    pkg: "{{ packages }}"
    state: present

- name: Install socksify if needed
  apt:
    pkg: "{{ packages_for_socks_proxy }}"
    state: present
  when: refstack_socks_gateway is defined and refstack_socks_port is defined

- name: Upgrade pip
  pip:
    name: pip
    state: latest

- name: Install required pip packages
  pip:
    name: "{{ item }}"
  with_items: "{{ pip_packages }}"

- name: Create refstack directory
  file:
    path: "{{ refstack_install_dir }}"
    state: directory
    mode: 0755

- name: Clone the RefStack project repo
  git:
    repo: "{{ refstack_repo_url }}"
    dest: "{{ refstack_install_dir }}"
    version: "{{ refstack_version }}"
