---
# module: refstack_install/tasks
# description: Install RefStack onto an Ubuntu 16.xx server

- include_tasks: install.yml
- include_tasks: query_openstack.yml
- include_tasks: configure.yml

- include_tasks: run.yml
  when: refstack_run
