---
# module: refstack_install/tasks/query_openstack
# description: Read some required ID values from the running OpenStack instance

- name: Gather facts about the previously created external network
  openstack.cloud.networks_info:
    auth:
      auth_url: "{{ refstack_openstack_keystone_public_url }}"
      username: "{{ refstack_openstack_admin_username }}"
      password: "{{ refstack_openstack_admin_password }}"
      project_name: "{{ refstack_openstack_project_name }}"
      domain_id: default
    validate_certs: no
    name: "{{ refstack_openstack_public_net_name }}"
  register: result
  no_log: True

- name: Save external network ID
  set_fact:
    refstack_openstack_public_net_id: "{{ result.networks[0].id | default(0) }}"

- name: Gather facts about the previously created Cirros image
  openstack.cloud.image_info:
    auth:
      auth_url: "{{ refstack_openstack_keystone_public_url }}"
      username: "{{ refstack_openstack_admin_username }}"
      password: "{{ refstack_openstack_admin_password }}"
      project_name: "{{ refstack_openstack_project_name }}"
      domain_id: default
    validate_certs: no
    image: "{{ refstack_openstack_image_name }}"
  register: result
  no_log: True

- name: Save cirros image ID
  set_fact:
    refstack_openstack_cirros_image_id: "{{ result.images[0].id | default(0) }}"

- name: Look for an alternate Cirros (or other) image
  openstack.cloud.image_info:
    auth:
      auth_url: "{{ refstack_openstack_keystone_public_url }}"
      username: "{{ refstack_openstack_admin_username }}"
      password: "{{ refstack_openstack_admin_password }}"
      project_name: "{{ refstack_openstack_project_name }}"
      domain_id: default
    validate_certs: no
    image: "{{ refstack_openstack_alternate_image_name }}"
  register: result
  no_log: True

- name: Save alternate image ID
  set_fact:
    refstack_openstack_cirros_alt_image_id: "{{ result.images[0].id | default(0) }}"
